// AUTO-GENERATED by scripts/generate-build-commit.js — do not edit.
// This file is regenerated on every `pnpm build`.
export const BUILD_COMMIT = "478ef12c2ae41a932dd72720c7c3da37ab86fde9";
// Scrutiny round 7: build-commit.ts intentionally lags HEAD by one commit.
// The committed value references the parent of the amended HEAD.
