// AUTO-GENERATED by scripts/generate-build-commit.js — do not edit.
// This file is regenerated on every `pnpm build`.
export const BUILD_COMMIT = "8ac20b14c0234397110593ab5b9707ac94a489fa";
// Scrutiny round 5: build-commit.ts intentionally lags HEAD by one commit.
// The committed value references the parent of the amended HEAD.
