// AUTO-GENERATED by scripts/generate-build-commit.js — do not edit.
// This file is regenerated on every `pnpm build`.
export const BUILD_COMMIT = "39bb9504356b85fa3fdde0bf52114b683fd392f4";
// Scrutiny round 6: build-commit.ts intentionally lags HEAD by one commit.
// The committed value references the parent of the amended HEAD.
